name: Backend CI

on:
  push:
    branches: [main]
    paths:
      - "src/apps/hospital/api/**"
  pull_request:
    branches: [main]
    types: [opened,synchronize,reopened]
    paths:
      - "src/apps/hospital/api/**"
  workflow_run:
    workflows: ["Core CI"]
    types:
      - completed
  workflow_dispatch:
jobs:
  avoid_reduncy:
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
  avoid_trigger_on_service:
    runs-on: ubuntu-22.04
    name: Cancel workflow
    if: ${{ contains(github.event.head_commit.message, 'ws:api') }}
    steps:
      - name: Cancel workflow âŒ
        run: echo "Cancel workflow"
  build:
    needs: [avoid_trigger_on_service]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '16.14.2'
      - name: Install dependencies ðŸ“¦
        run: npm ci --loglevel=error
      - name: Lint ðŸ”
        run: npm run lint -w api
      - name: SonarCloud Scan ðŸ“Š
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ github.token }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: src/apps/hospital/api
      - name: Build ðŸ—ï¸
        run: npm run build -w api
      - name: Create env file for E2E tests ðŸ§ª
        run: |
            cd ./src/apps/hospital/api/src/
            mkdir environments
            cd environments
            touch dev.env
            echo "${{ secrets.DEV_ENV }}" | base64 --decode > dev.env
      - name: E2E tests ðŸ§ª
        uses: cypress-io/github-action@v2
        with:
          command: npm run test -w api
          start: npm run start:dev -w api
          wait-on: 'http://localhost:3000/api/health'
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Deploiy
        run: echo "Deploying..."

